// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs2oDrVfRj1jUfNBHvVqnLGt9OgnORer0',
    appId: '1:306015957702:web:6cd77bd00d96a5ebec1dc7',
    messagingSenderId: '306015957702',
    projectId: 'redditatte',
    authDomain: 'redditatte.firebaseapp.com',
    storageBucket: 'redditatte.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPOGmCY8KY-FXuy7A9rywMEJ3Ev1j8iwQ',
    appId: '1:306015957702:android:e63669789a3cdfdfec1dc7',
    messagingSenderId: '306015957702',
    projectId: 'redditatte',
    storageBucket: 'redditatte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4VcEMiEsUEKPIxsIldwPwT3MG4HfvWQA',
    appId: '1:306015957702:ios:99bd7c861773b9ccec1dc7',
    messagingSenderId: '306015957702',
    projectId: 'redditatte',
    storageBucket: 'redditatte.firebasestorage.app',
    iosBundleId: 'com.example.redditAttempt2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4VcEMiEsUEKPIxsIldwPwT3MG4HfvWQA',
    appId: '1:306015957702:ios:99bd7c861773b9ccec1dc7',
    messagingSenderId: '306015957702',
    projectId: 'redditatte',
    storageBucket: 'redditatte.firebasestorage.app',
    iosBundleId: 'com.example.redditAttempt2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs2oDrVfRj1jUfNBHvVqnLGt9OgnORer0',
    appId: '1:306015957702:web:684b36d22dbd1754ec1dc7',
    messagingSenderId: '306015957702',
    projectId: 'redditatte',
    authDomain: 'redditatte.firebaseapp.com',
    storageBucket: 'redditatte.firebasestorage.app',
  );
}
